# Generated by Django 3.1.4 on 2020-12-28 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('fecha', models.DateField(auto_now=True)),
                ('autor', models.CharField(choices=[('Augusto', 'Augusto'), ('Alex', 'Alex'), ('Mani', 'Mani')], max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
    ]
