# Generated by Django 3.1.4 on 2020-12-28 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clases',
            new_name='Clase',
        ),
    ]
