# Generated by Django 3.1.4 on 2020-12-28 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0003_auto_20201228_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='titulo',
            field=models.CharField(max_length=100, null=True, verbose_name='titulo'),
        ),
    ]
