# Generated by Django 3.1.4 on 2020-12-29 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0004_clase_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='pdf',
            field=models.FileField(null=True, upload_to='static/media'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
