# Generated by Django 3.0.6 on 2020-12-23 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_cuenta', models.IntegerField()),
                ('Apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('Apellido2', models.CharField(max_length=50, verbose_name='Apellido 2')),
                ('Nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('Carrera', models.CharField(max_length=50, verbose_name='Carrera')),
                ('Gen', models.SmallIntegerField()),
                ('Calif', models.FloatField()),
                ('Correo', models.EmailField(max_length=254)),
            ],
        ),
    ]
