# Generated by Django 3.0.6 on 2020-12-23 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proba1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='Apellido',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='Apellido2',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='Calif',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='Carrera',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='Correo',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='Gen',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='Nombre',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='no_cuenta',
        ),
        migrations.AddField(
            model_name='documento',
            name='contenido',
            field=models.CharField(max_length=50, null=True, verbose_name='Contenido'),
        ),
        migrations.AddField(
            model_name='documento',
            name='orden',
            field=models.CharField(max_length=50, null=True, verbose_name='Orden'),
        ),
    ]
