# Generated by Django 3.0.6 on 2020-12-23 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proba1', '0002_auto_20201223_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='Generacion',
            field=models.FloatField(null=True, verbose_name='Generacion'),
        ),
    ]
