# Generated by Django 3.0.6 on 2020-12-23 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proba1', '0003_documento_generacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='contenido',
        ),
        migrations.AddField(
            model_name='documento',
            name='Apellido',
            field=models.CharField(max_length=50, null=True, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='Generacion',
            field=models.FloatField(null=True),
        ),
    ]
