# Generated by Django 3.0.6 on 2020-12-23 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proba1', '0004_auto_20201223_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='no_Cuenta',
            field=models.IntegerField(null=True, verbose_name='Cuenta'),
        ),
    ]
