# Generated by Django 3.0.6 on 2020-12-23 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proba1', '0005_documento_no_cuenta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='no_Cuenta',
            new_name='Cuenta',
        ),
    ]
