# Generated by Django 3.0.6 on 2020-12-23 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proba1', '0006_auto_20201223_0248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='orden',
        ),
        migrations.AddField(
            model_name='documento',
            name='Apellido2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='Carrera',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='Nombre',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
