# Generated by Django 3.0.6 on 2020-12-23 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proba1', '0007_auto_20201223_0250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='Apellido2',
            new_name='Apellido 2',
        ),
    ]
