# Generated by Django 3.0.6 on 2020-12-23 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proba1', '0008_auto_20201223_0252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='Generacion',
            new_name='Gen',
        ),
        migrations.AddField(
            model_name='documento',
            name='Calif',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='Correo',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
