# Generated by Django 3.0.6 on 2020-12-23 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proba1', '0009_auto_20201223_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='Mod',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
