# Generated by Django 3.0.6 on 2020-12-23 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proba1', '0011_auto_20201223_0303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'ordering': ['Apellido']},
        ),
    ]
