# Generated by Django 3.1.4 on 2020-12-25 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proba1', '0012_auto_20201223_0438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='Calif',
            new_name='DataCamp',
        ),
        migrations.AddField(
            model_name='documento',
            name='Equipo',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='Examen1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='Examen2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='Examen3',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='Puntos_Extras',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='Tarea1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='Tarea2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='Tarea3',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='Tarea_examen',
            field=models.FloatField(null=True),
        ),
    ]
