# Generated by Django 3.1.4 on 2020-12-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proba1', '0013_auto_20201225_0523'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'ordering': ['Apellido', '-Equipo'], 'verbose_name': 'Alumnos'},
        ),
        migrations.AlterField(
            model_name='documento',
            name='DataCamp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='Equipo',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='Examen1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='Examen2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='Examen3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='Puntos_Extras',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='Tarea1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='Tarea2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='Tarea3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='Tarea_examen',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
