# Generated by Django 3.0.6 on 2020-12-23 05:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('import_2', '0002_historicalarchivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalarchivo',
            name='history_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
