# Generated by Django 3.0.6 on 2020-12-23 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('import_2', '0004_auto_20201223_0510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivo',
            name='changed_by',
        ),
        migrations.DeleteModel(
            name='HistoricalArchivo',
        ),
    ]
