# Generated by Django 3.0.6 on 2020-12-23 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('import_2', '0006_historicalarchivo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalArchivo',
        ),
    ]
