# Generated by Django 3.0.6 on 2020-12-23 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_2', '0007_delete_historicalarchivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='local_id',
            field=models.CharField(max_length=120, null=True, unique=True),
        ),
    ]
