# Generated by Django 3.0.6 on 2020-12-23 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('import_2', '0008_archivo_local_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivo',
            name='local_id',
        ),
    ]
