# Generated by Django 3.0.6 on 2020-12-23 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_2', '0009_remove_archivo_local_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='userid',
            field=models.IntegerField(null=True),
        ),
    ]
