# Generated by Django 3.0.6 on 2020-12-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_2', '0010_archivo_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivo',
            name='id',
        ),
        migrations.AlterField(
            model_name='archivo',
            name='userid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
